#include <iostream>
#include <ctime>
#include <cstdlib>
using namespace std;

//Compiler version g++ 6.3.0
int main()
{
    srand(time(0));
    int secret=1+(rand()%100);
    cout<<"Let's guess the number generated by the system"<<endl;
    cout<<"Guess the number"<<endl;
    int attempts=0;
    int guess;
    do {
      cin>>guess;
      if(guess>secret){
        cout<<"Too high"<<endl<<"Enter another guess"<<endl;
      }
      else if(guess<secret){
        cout<<"Too low"<<endl<<"Enter another guess"<<endl;
      }
      attempts++;
    } while(guess!=secret);
    cout<<"Yess!! the number is "<<secret<<endl<<"You got it in "<<attempts<<" attempts"<<endl;
}