#include <iostream>
#include <ctime>
#include <cstdlib>
using namespace std;


int main()
{
    srand(time(0));
    int secret=1+(rand()%100);
    cout<<"|| Guess the number generated by the system ||"<<endl;
    cout<<endl;
    cout<<"Enter a guess:"<<endl;
    int attempts=0;
    int guess;
    do {
      cin>>guess;
      if(guess>secret){
        cout<<"Too high"<<endl<<"Enter another guess:"<<endl;
      }
      else if(guess<secret){
        cout<<"Too low"<<endl<<"Enter another guess:"<<endl;
      }
      attempts++;
    } while(guess!=secret);
    cout<<"Yess!! the number is "<<secret<<endl<<"You got it in "<<attempts<<" attempts"<<endl;
}"<<endl;
}
}